### ISSUE TITLE
warning AppBoy shared instance

### ISSUE THREAD

**Issue by qclmnt** [Appboy/appboy-segment-ios#10]
Hi,

We are experiencing a weird warning : 

```
********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **     before Appboy was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
********************************************
```

but AppBoy is initialized before : 

```
// Init Segment
    SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:@"**********"];
    configuration.shouldUseLocationServices = NO;
    [configuration use:[SEGAppboyIntegrationFactory instance]];
    [SEGAnalytics setupWithConfiguration:configuration];
    [SEGAnalytics debug:NO];
    
[[Appboy sharedInstance] registerPushToken:****];
```

SDK : Segment-Appboy
SDK Version : 
```
 - Segment-Appboy (1.0.4):
    - Analytics (~> 3.0)
    - Appboy-iOS-SDK (= 2.28.0)
```
iOS : 10

**Comment by chshapiro** [comment]
Hey @qclmnt,
According to your code snippet,  the warning can be due to `[[Appboy sharedInstance] registerPushToken:****];` getting called before Appboy is fully initialized. You should be able to confirm that by adding a breakpoint and checking the `[Appboy sharedInstance]` object. 

Is there a reason you're not following the documentation in https://segment.com/docs/integrations/appboy/#integrating-push?

Alternatively, you can use the following code https://segment.com/docs/sources/mobile/ios/#how-do-i-know-when-an-integration-is-initialized- which will only call the method once Appboy has been initialized.

Thanks,
Chava

**Comment by chshapiro** [comment]
Hey @qclmnt, 

Were you able to confirm that this solution worked for you? Do you still have issues or questions? Please let us know if this is still a problem for you.

Thanks, Chava

**Comment by qclmnt** [comment]
Hi @chshapiro, 

sorry for the late response. 
This link : https://segment.com/docs/sources/mobile/ios/#how-do-i-know-when-an-integration-is-initialized- actually works great and fix the bug.

But I just fixed the doc, on the doc it's `integration.name` instead of: `integration`

The good solution : 
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(integrationDidStart:) name:SEGAnalyticsIntegrationDidStart object:nil];

- (void)integrationDidStart:(nonnull NSNotification *)notification
{
    NSString *integration = notification.object;

    if ([integration isEqualToString:@"Mixpanel"]) {
        // Call Mixpanel library methods here.
    }
}
```
