### ISSUE TITLE
Full pod fights Xcode settings and always dirties git

### ISSUE THREAD

**Issue by bricepollock** [Appboy/appboy-segment-ios#31]
Summary: 
When I install the full pod:
pod "Segment-Appboy"

It modifies a bunch of settings in the project. If I commit these changes and open Xcode, then Xcode modifies a bunch of settings back...

[patch.txt](https://github.com/Appboy/appboy-segment-ios/files/4182627/patch.txt)

Critical Issue: 
Our CI continuously fails b/c we try to upload a build after pod installing, but it dirties git and the upload fails.

Steps:
1. Create a single app project
2. Create a Podfile
3. Add "Segment-Appboy" to the Podfile
4. Run pod install
5. Commit all changes
6. Open workspace in Xcode 11.3 or 11.2
7. Check 'git status'
8. A number of lines have changed in the 'Pods/Pods.xcodeproj/project.pbxproj'
9. Commit all changes
10. Repeat 4-9 to see Xcode and the appboy pod continually fight over the Pods.xcodeproj settings

Context:
This does not ever happen with other pods. 
This does not happen with "Segment-Appboy/Core"

Suggested fix:
Replicate the settings for the Core pod into the main SDK pod. 

I have a test project zip, but cannot upload it to GitHub due to size

**Comment by Bucimis** [comment]
@bricepollock what version of cocoapods are you using?

**Comment by bricepollock** [comment]
cocoapods (1.8.4)
cocoapods-check (1.1.0)
cocoapods-core (1.8.4)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0, 1.2.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.1)
cocoapods-try (1.1.0)

**Comment by ndonald2** [comment]
I'm on @bricepollock's team and I helped dive into this today. Through a lot of guess and check, I made some interesting discoveries. The issue is actually rooted in `Appboy-iOS-SDK`, not the Segment integration (happy to open an issue there instead if preferred, @Bucimis).

The thing that's triggering the git fight appears to be the way the localized strings files are included. By changing the `Appboy-iOS-SDK.podspec` file so that localized strings files are _not_ included, the issue goes away. It also goes away if the `.lproj` directories are included as folders instead of just including the strings files, as is achieved in [this example](https://github.com/betterup/appboy-ios-sdk/blob/unmaintained/Appboy-iOS-SDK.podspec) in a fork I made of the repo. However I'm not sure if including the .lproj directories themselves vs the strings files breaks anything in the SDK - I would assume it does since the bundle resource lookup would be different.

Hopefully that is a clue or nudge in the right direction. From some surface level investigation it seems that other pods, and even AppboyKit itself, tend to avoid this issue by including a `.bundle` instead of files in the raw. I tried to use [`resource_bundle`](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles) in the podspec but that didn't change anything, I think the bundle might need to be pre-created in the repo itself.

Please let me know if I can provide any more info to help debug this.

**Comment by ndonald2** [comment]
> it seems that other pods, and even AppboyKit itself, tend to avoid this issue by including a .bundle instead of files in the raw

This seems to be the key - would it be possible to use pre-built resource bundles for the AppBoy UI stuff instead of just loose resource files? Like how it's done here: https://github.com/Appboy/appboy-ios-sdk/tree/master/AppboyKit/Appboy.bundle

**Comment by bricepollock** [comment]
In support conversations, Braze claims this is the fault of Cocoapods. Irregardless of the issue only happening with the Appboy SDK...

You can follow the cocoapods issue here: https://github.com/CocoaPods/CocoaPods/issues/8689

**Comment by bricepollock** [comment]
Can no longer reproduce with:
```
        pod 'Appboy-iOS-SDK', '~> 3.26.1'
        pod 'Segment-Appboy', '~> 3.3.0'
```
