### ISSUE TITLE
Support screen method

### ISSUE THREAD

**Issue by jskrepnek** [Appboy/appboy-segment-ios#37]
Is there a reason why this method is not supported?

**Comment by davidbielik** [comment]
Hi @jskrepnek thanks for raising this. We don't support the screen method as our SDK wouldn't typically need the equivalent of "pageview/screen" tracking that analytics companies use, since our messaging is trigger/event based.

I'd recommend reaching out to our support team with this feedback to help you with your specific scenario and environment, while I'll log this as product feedback. Feel free to re-open if you have any followup!
