### ISSUE TITLE
Shared instance sometimes undefined

### ISSUE THREAD

**Issue by igorkoho** [Appboy/appboy-segment-ios#70]
Hi Braze crew,

We've been getting issues tracked in our mobile ionic-capacitor app (we use the sdk v4.5.0) where sometimes when we call a method on the shared instance, it doesn't exist. I've not been able to so far reproduce this issue ourselves (even calling a method on the shared instance from the app boot-up works in my experience), but our sentry reports show that _some_ people do in fact run into this issue.

Would be curious to find out how we can make sure that the shared instance is instantiated correctly each time, so that we don't run into this issue.

Thanks!

**Comment by lowip** [comment]
Hi @igorkoho,

The `sharedInstance` is `nil` after calling one of these methods:
- [`wipeDataAndDisableForAppRun`](https://appboy.github.io/appboy-ios-sdk/docs/interface_appboy.html#ac8d580f60ec0608cd91240a8a3aa23a3)
- [`disableSDK`](https://appboy.github.io/appboy-ios-sdk/docs/interface_appboy.html#a8d3b78a98420713d8590ed63c9172733)

Are you making use of any of those APIs in your application?

**Comment by lowip** [comment]
@igorkoho, the behavior you're describing seems to be due to the asynchronous nature of the Segment integration. On launch, the Segment SDK will fetch its configuration, cache it and will read which device-mode destinations are enabled for your integration (e.g Braze).

Until the Segment SDK has received the initial configuration, the Appboy/Braze SDK won't be initialized. Unfortunately, I don't think there's anything we can do on our side do modify that behavior.

Please let us know if you have more questions.

**Comment by lowip** [comment]
> Sorry, are you implying there is something we could do on our side to fix this? If so, could you provide more insight as to what that is?

So the behavior when integrating our SDK via segment is similar to any other device-mode destinations. As you chose to use Segment to manage the Braze SDK lifetime, the Segment SDK must fetch which destinations are currently enabled.

On your application first launch (after a fresh install):
- Segment doesn't know yet which destination are enabled
  - The Appboy/Braze SDK is not initialized yet
- Segment starts fetching its own configuration
  - While that request is in-flight, any call to `Appboy.sharedInstance` will fails as Segment is responsible for starting our SDK
  - Integrating push related features requires you to call some methods on `Appboy.sharedInstance`
    - Specifically `Appboy.pushAuthorizationFromUserNotificationCenter:`
- Once Segment has fetched its configuration, it starts the Appboy/Braze SDK and `Appboy.sharedInstance` becomes valid
- On subsequent app launches, Segment will use its cached configuration and will start the Appboy/Braze SDK synchronously

As you rely on Segment to configure our SDK, you cannot reliably use the Appboy instance until Segment itself is fully setup. This issue manifests itself until Segment has successfully performed its initial configuration sync.

> Also, isn't there a way that the sdk itself could delay initialization until it has downloaded the configuration?

This is actually what's happening here, and is the root of the issue. Our SDK is initialized asynchronously because of Segment asynchronous behavior.

The errors you are seeing are likely due to your own app calls to `Appboy.sharedInstance` methods while the Segment initial sync is in-flight.

Let me know if that answer your question.

**Comment by igorkoho** [comment]
> While that request is in-flight, any call to Appboy.sharedInstance will fails as Segment is responsible for starting our SDK

Is this to suggest that references to shared instance are expected to fail during initial boot, but after the configuration fetch has been completed, the shared instance should be available?

> On subsequent app launches, Segment will use its cached configuration and will start the Appboy/Braze SDK synchronously

To be clear, the shared instance doesn't become available at any point during the lifetime of the app on first boot, or even second boot. Only on third boot does it work as expected in my tests. Furthermore, calls that _don't_ rely on the shared instance work from the very beginning. So, the user is able to pull up the content card view and see the no content card state of it on first boot, but requests to refresh content cards for instance fail since the shared instance isn't defined.

Most importantly though, in your opinion, is there a way to make the braze content cards feature work on first boot of the app, even if initialized via the segment-appboy sdk?

**Comment by igorkoho** [comment]
Hey @lowip, curious if there's any update on the above?

**Comment by hokstuff** [comment]
You can follow the same instructions while using the `appboy-segment-ios` plugin as well (e.g. you can reference [our sample app integration here)](https://github.com/Appboy/appboy-segment-ios/blob/dc659b70f2b432f8c70fda869b27eac2acb688fe/CocoapodsExample/Segment-Appboy/Segment-Appboy-Info.plist#L7). For any further questions, you can reach out to the Support team - thank you!

**Comment by hokstuff** [comment]
Hello,

I am closing out this issue due to inactivity. You can use [this updated repository](https://github.com/braze-inc/braze-segment-swift) which uses the modern Braze Swift SDK and Segment's Swift SDK.

Thanks!
